name: visual_detector_ai
description: "A Flutter package that uses AI to detect and identify objects in images."
version: 1.0.0
homepage: https://github.com/ibragimov05/visual_detector_ai

environment:
  sdk: ^3.5.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_generative_ai: ^0.4.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
